/robot_news_station_a:
  ros__parameters:
    robot_name: "A"
/robot_news_station_b:
  ros__parameters:
    robot_name: "B"
/robot_news_station_c:
  ros__parameters:
    robot_name: "C"
/robot_news_station_d:
  ros__parameters:
    robot_name: "D"
/robot_news_station_e:
  ros__parameters:
    robot_name: "E"
